version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'app_perf'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
    env_file:
      - '.env.docker'
    links:
      - 'postgres'

  agent:
    depends_on:
      - 'website'
    build: .
    command: bundle exec app_perf_agent --host website:5000 --license-key e47a7331-77cd-4ea0-8be1-b4130255a3a8 -f

volumes:
  redis:
  postgres:
